/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateSampleTestArgs } from "./CreateSampleTestArgs";
import { UpdateSampleTestArgs } from "./UpdateSampleTestArgs";
import { DeleteSampleTestArgs } from "./DeleteSampleTestArgs";
import { SampleTestFindManyArgs } from "./SampleTestFindManyArgs";
import { SampleTestFindUniqueArgs } from "./SampleTestFindUniqueArgs";
import { SampleTest } from "./SampleTest";
import { SampleTestService } from "../sampleTest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SampleTest)
export class SampleTestResolverBase {
  constructor(
    protected readonly service: SampleTestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SampleTest",
    action: "read",
    possession: "any",
  })
  async _sampleTestsMeta(
    @graphql.Args() args: SampleTestFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SampleTest])
  @nestAccessControl.UseRoles({
    resource: "SampleTest",
    action: "read",
    possession: "any",
  })
  async sampleTests(
    @graphql.Args() args: SampleTestFindManyArgs
  ): Promise<SampleTest[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SampleTest, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SampleTest",
    action: "read",
    possession: "own",
  })
  async sampleTest(
    @graphql.Args() args: SampleTestFindUniqueArgs
  ): Promise<SampleTest | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SampleTest)
  @nestAccessControl.UseRoles({
    resource: "SampleTest",
    action: "create",
    possession: "any",
  })
  async createSampleTest(
    @graphql.Args() args: CreateSampleTestArgs
  ): Promise<SampleTest> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SampleTest)
  @nestAccessControl.UseRoles({
    resource: "SampleTest",
    action: "update",
    possession: "any",
  })
  async updateSampleTest(
    @graphql.Args() args: UpdateSampleTestArgs
  ): Promise<SampleTest | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SampleTest)
  @nestAccessControl.UseRoles({
    resource: "SampleTest",
    action: "delete",
    possession: "any",
  })
  async deleteSampleTest(
    @graphql.Args() args: DeleteSampleTestArgs
  ): Promise<SampleTest | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
